name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install FFmpeg and lsof
      run: |
        sudo apt update
        sudo apt install -y ffmpeg lsof

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Check processes on port 8000
      run: |
        echo "Checking for processes using port 8000"
        sudo lsof -i:8000

    - name: Kill processes using port 8000 if any
      run: |
        PIDS=$(sudo lsof -t -i:8000)
        if [ ! -z "$PIDS" ]; then
          echo "Killing processes on port 8000"
          sudo kill -9 $PIDS
        else
          echo "No processes found on port 8000"
        fi

    - name: Start FastAPI server
      run: |
        screen -dm uvicorn 1.main:app --host 127.0.0.1 --port 8000
        sleep 10

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -v